# Nombre del paquete
package_name: Ramdom-Forest-Classifier

# Variable objetivo
target: rango_precios_var_dependiente

# Variables de características (features)
features:
  - FID_puntos_comerciales
  - municipio
  - departamen
  - cod_depart
  - cod_dane_mpio
  - categoria_mtv11
  - cod_precios
  - Vigencia
  - FID_ECOSISTEMAS_2017
  - OBJECTID_1
  - TIPO_ECOSI
  - GRADO_TRAN
  - GRAN_BIOMA
  - BIOMA_PREL
  - BIOMA_IAvH
  - ECOS_SINTE
  - ECOS_GENER
  - UNIDAD_SIN
  - AMBIENTE_A
  - SUBSISTEMA
  - ZONA_HIDRO
  - ORIGEN
  - TIPO_AGUA
  - CLIMA
  - PAISAJE
  - RELIEVE
  - SUELOS
  - AMB_EDAFOG
  - DESC_AMB_E
  - COBERTURA
  - UNI_BIOTIC
  - ANFIBIOS
  - AVES
  - MAGNOLIOPS
  - MAMIFEROS
  - REPTILES
  - No_Anfibio
  - No_Aves
  - No_Magnoli
  - No_Mamifer
  - No_Reptile
  - SHAPE_Leng
  - AH
  - NOMAH
  - ZH
  - NOMZH
  - SZH
  - NOMSZH
  - IPHE_VALOR
  - IPHE_CATEGORIA
  - IEUA_VALOR
  - IUEA_CATEGORIA
  - HHV2020
  - HHA_2020
  - IARC_VALOR
  - IARC_CATEGORIA
  - IUA_MEDIO_VALOR
  - IUA_MEDIO_CAREGORIA
  - IUA_SECO_VALOR
  - IUA_sECO_CATEGORIA
  - IACAL_M
  - CATIACAL_M
  - IACAL_S
  - CIACAL_S
  - irh
  - cat
  - IVH_MEDIO_VALOR
  - IVH_MEDIO_CATEGORIA
  - IVH_SECO_VALOR
  - IVH_SECO_CATEGORIA
  - FID_Correlacion_5048_md
  - UCSuelo
  - S_UC
  - S_UC_FASE
  - OTRAS_FA_1
  - PENDIENT_1
  - EROSION_1
  - S_CLIMA
  - CLIMA_1
  - S_PAISAJE
  - PAISAJE_1
  - TIPO_RELIE
  - MATERIAL_P
  - SUBGRUPO
  - PERFILES
  - PORCENTAJE
  - PROFUNDIDA
  - TEXTURA
  - FERTILIDAD
  - ACIDEZ
  - DRENAJE
  - HUMEDAD
  - ALUMINIO
  - SALINIDAD_1
  - SODICIDAD
  - SATURACION
  - CALCAREO
  - AREA_HA_1
  - Significad
  - FID_1
  - layer
  - ORIG_FID_1
  - FID_Cobertura_tierra_2018
  - codigo
  - leyenda
  - area_Ha_12
  - CLAS_UPRA
  - FA
  - COBERTURAS_CON_USO_AGRO
  - AF

# Fracción del conjunto de prueba
test_size: 0.25

# Semilla para reproducibilidad
random_state: 42

# Hiperparámetros del modelo
n_estimators: 850
max_depth: 19

# Variables categóricas
categorical_vars:
  - municipio
  - departamen
  - categoria_mtv11
  - TIPO_ECOSI
  - GRAN_BIOMA
  - BIOMA_PREL
  - CLIMA
  - PAISAJE
  - RELIEVE
  - COBERTURA

# Mapeo de variables (si aplica)
qual_mappings:
  Attrited Customer: 1
  Existing Customer: 0
